Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2020-08, with the labels that each got.

#53 Update pipeline to release when we tag to github and documentation for release
  .circleci/config.yml
  README.md
Labels: 4: Reviews Complete, kind/cleanup, release-note-none

#57 Add Postgres database options
  go.mod
  go.sum
  server/command_create.go
  server/command_list_test.go
  server/command_status.go
  server/command_test.go
  server/configuration.go
  server/utils.go
Labels: 4: Reviews Complete, kind/feature, release-note

#58 Update web packages and bump plugin version
  plugin.json
  server/manifest.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/manifest.js
Labels: 4: Reviews Complete, kind/cleanup, release-note
