Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2020-06, with the labels that each got.

#48 Default cloud servers to use aws multitenant
  server/command_create.go
Labels: 2: Dev Review

#49 Bump version to 0.1.14
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete

#50 Add release notify action and pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/notify-release.yml
Labels: 4: Reviews Complete, kind/documentation, release-note-none

#51 block installations if is less than version 5.12.0
  go.mod
  go.sum
  server/command_create.go
  server/command_test.go
  server/utils.go
Labels: 4: Reviews Complete, kind/feature, release-note
