Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2021-03, with the labels that each got.

#72 Cloud Plugin: handle version checks with new docker repository options
  server/command_create.go
  server/command_upgrade.go
Labels: 4: Reviews Complete, kind/bug, release-note

#73 Update dependencies and plugin version
  go.mod
  go.sum
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete, kind/cleanup, release-note

#75 Fix version and image check for create command
  server/command_create.go
Labels: 2: Dev Review, kind/bug, release-note

#76 handle http protocols if included with the import domain value
  server/command_import.go
  server/command_import_test.go
Labels: 2: Dev Review, kind/feature, release-note

#77 Add test to import command to see if installation has already been imported
  server/command_import.go
  server/command_import_test.go
  server/command_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#78 Bump version to v0.1.20
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete, release-note-none
