Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2022-06, with the labels that each got.

#96 Bump version to 0.1.23
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: release-note-none

#98 MM-45027 - Log errors to debug a webapp crash
  server/api.go
Labels: 4: Reviews Complete, release-note-none

#100 MM-45027 - More debugging; temporary fix
  webapp/src/actions/index.js
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/components/user_attribute/user_attribute.jsx
Labels: 2: Dev Review, release-note-none

#101 MM-45027 - Fix: Cloud plugin causing crash on webapp
  Makefile
  plugin.json
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/sidebar_right/index.js
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/components/user_attribute/index.js
  webapp/src/components/user_attribute/user_attribute.jsx
  webapp/src/reducers/index.js
  webapp/src/selectors.js
Labels: 4: Reviews Complete, release-note

#99 Bump version to 0.1.24
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete, release-note-none
