Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2022-04, with the labels that each got.

#91 Change default filestore and DB
  server/command_create.go
Labels: release-note, kind/chore

#92 fix minor typo
  server/command.go
Labels: release-note-none

#93 [MM-40214] Implement App Bar component
  Makefile
  public/app-bar-icon.png
  webapp/src/index.js
Labels: 4: Reviews Complete, kind/feature, release-note

#94 Fix email check
  server/command.go
Labels: 4: Reviews Complete, release-note-none
