Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2023-06, with the labels that each got.

#124 [CLD-5829] Quietly add back support for certain database types
  server/command_create.go
  server/command_create_test.go
  server/utils.go
Labels: 4: Reviews Complete, release-note

#126 Add Installation log links to the webapp
  server/api.go
  webapp/src/components/sidebar_right/sidebar_right.jsx
Labels: release-note

#125 Change default admin username and simplify test-data
  server/setup.go
Labels: release-note

#127 Bump version to v0.1.29
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: release-note-none
