Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2023-11, with the labels that each got.

#139 feat: Add new repository for cloud plugin
  server/configuration.go
Labels: kind/feature, release-note-none

#141 Cleanup test data generation logic
  server/setup.go
Labels: 4: Reviews Complete, kind/bug, release-note

#142 Update various versions and dependencies
  go.mod
  go.sum
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete, release-note, kind/chore

#140 Add installation restart command
  server/command.go
  server/command_restart.go
  server/command_restart_test.go
Labels: 2: Dev Review, kind/feature, release-note

#143 Display Service Environment configuration in RHS
  server/api.go
  server/command_deletion_lock.go
  server/command_hibernate.go
  server/command_list.go
  server/command_list_test.go
  server/command_wakeup.go
  webapp/src/components/sidebar_right/sidebar_right.jsx
Labels: 4: Reviews Complete, kind/feature, release-note

#144 [CLD-6593] Add support for running webapp tests in CI
  Makefile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/channel_header_button/channel_header_button.test.tsx
  webapp/src/components/channel_header_button/channel_header_button.tsx
  webapp/src/components/sidebar_right/deletion_unlock_confirmation_modal.test.jsx
  webapp/src/components/sidebar_right/sidebar_right.test.jsx
  webapp/src/components/state_badge.jsx
  webapp/src/components/user_attribute/user_attribute.test.jsx
Labels: release-note
