Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2023-04, with the labels that each got.

#118 [MM-51743] Add plugin options for default database and filestore
  plugin.json
  server/command.go
  server/command_create.go
  server/configuration.go
Labels: release-note

#120 Use new docker test repos
  server/command_create.go
  server/command_create_test.go
  server/command_upgrade_test.go
Labels: 2: Dev Review, release-note

#122 Use test licenses for certain docker repos
  plugin.json
  server/command_create.go
  server/command_upgrade.go
  server/configuration.go
  server/configuration_test.go
Labels: 4: Reviews Complete, kind/feature, release-note

#121 Bump version to v0.1.28
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review, release-note-none
