Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2023-02, with the labels that each got.

#109 [MM-50277] fix: validate installation size
  server/command_create.go
  server/command_create_test.go
  server/command_upgrade.go
  server/command_upgrade_test.go
  server/utils.go
Labels: 2: Dev Review, kind/bug, release-note

#110 [MM-45035] Updated http client to use mattermost-redux
  webapp/package-lock.json
  webapp/package.json
  webapp/src/client/client.js
Labels: 4: Reviews Complete, kind/bug, release-note

#108 [MM-49990] Remove database options from the cloud plugin
  .gitignore
  server/command_create.go
  server/command_create_test.go
  server/utils.go
Labels: 2: Dev Review, release-note
