Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2023-03, with the labels that each got.

#107 Migrate from CircleCI to Github Actions
  .circleci/config.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .nvmrc
Labels: 2: Dev Review, kind/feature, release-note-none

#113 Prettify the right hand sidebar
  webapp/src/components/sidebar_right/sidebar_right.jsx
Labels: 4: Reviews Complete, release-note

#114 feat: provide grafana links for created installs
  server/webhook.go
Labels: 2: Dev Review, kind/feature, release-note

#115 chore: change default database for new installs
  server/command_create.go
Labels: kind/bug, release-note

#117 [MM-51751] Fix regex for tags trigger in CI/CD
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 4: Reviews Complete, release-note-none
