Repository mattermost/mattermost-plugin-cloud, pull requests merged in 2024-01, with the labels that each got.

#148 Add installation restart button to UI
  webapp/src/actions/index.js
  webapp/src/client/client.js
  webapp/src/components/sidebar_right/confirmation_modal.jsx
  webapp/src/components/sidebar_right/confirmation_modal.scss
  webapp/src/components/sidebar_right/confirmation_modal.test.jsx
  webapp/src/components/sidebar_right/index.js
  webapp/src/components/sidebar_right/sidebar_right.jsx
  webapp/src/components/sidebar_right/sidebar_right.test.jsx
Labels: 4: Reviews Complete, release-note

#150 [CLD-6815] Fix console errors when first loading user and shared installs
  webapp/src/actions/index.js
Labels: 4: Reviews Complete, release-note-none

#149 Bump plugin version to v0.1.34
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete, release-note-none

#151 [CLD-6962] Remove bottom border on confirmation modal
  webapp/src/components/sidebar_right/confirmation_modal.scss
Labels: 4: Reviews Complete, release-note-none

#152 Don't build server for Windows environments
  Makefile
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: release-note-none
